from utils.app_config import APP_NAME

TITLE_ERROR = "Error"
TITLE_UNSAVED = "Unsaved Changes"
TITLE_TRANSPARENCY = "Transparency"
TITLE_CLEAR_CANVAS = "Clear Canvas"
TITLE_SHIFT_CANVAS = "Shift Canvas"
TITLE_NEW_CANVAS = "New Canvas"
TITLE_ABOUT = "About Tilf"
TITLE_OPEN_IMAGE = "Open Image"
TITLE_SAVE_IMAGE = "Save Image"
TITLE_PRIMARY_COLOR = "Choose Primary Color"
TITLE_SECONDARY_COLOR = "Choose Secondary Color"
TITLE_GRID_COLOR = "Choose Grid Color"
TITLE_RECOVERY = "Recover Autosave"

MENU_FILE = "File"
MENU_EDIT = "Edit"
MENU_VIEW = "View"
MENU_HELP = "Help"
MENU_ZOOM_PRESETS = "Zoom Presets"

ACTION_ABOUT = "About Tilf"
ACTION_ACTUAL_SIZE = "100%"
ACTION_CHECK_UPDATES = "Check for Updates"
ACTION_CLEAR_CANVAS = "Clear Canvas"
ACTION_FIT_TO_WINDOW = "Fit to Window"
ACTION_GRID_COLOR = "Grid Color"
ACTION_NEW = "New"
ACTION_OPEN = "Open"
ACTION_QUIT = "Quit"
ACTION_REDO = "Redo"
ACTION_RESET_ZOOM = "Reset Zoom"
ACTION_SAVE = "Save"
ACTION_UNDO = "Undo"
ACTION_ZOOM_IN = "Zoom In"
ACTION_ZOOM_OUT = "Zoom Out"

MSG_FAILED_LOAD = "Failed to load the image."
MSG_FAILED_SAVE_FMT = "Failed to save the image to: {path}"
MSG_FILE_SAVED = "Image saved."
MSG_DISCARD_CHANGES = "You have unsaved changes. Do you want to continue and discard them?"
MSG_SAVE_BEFORE_QUIT = "You have unsaved changes. Do you want to save before quitting?"
MSG_TRANSPARENCY_PROMPT = "Save with a transparent background?"
MSG_CLEAR_CONFIRM = "Are you sure you want to clear the canvas?"
MSG_SHIFT_CANVAS = "Shift canvas 1px to the:"
MSG_NEW_CANVAS_HELP = (
    "Canvas size is the final image size. Changing tile columns, rows, or tile size creates an exact tile grid."
)
MSG_RECOVERY_AVAILABLE_FMT = "A recovery file was found: {filename}. Open it now?"
MSG_UPDATE_AVAILABLE_FMT = "Tilf {latest_version} is available. You are currently using {current_version}."
MSG_UPDATE_CURRENT_FMT = "You are already using the latest version: {current_version}."
MSG_UPDATE_CHECK_FAILED_FMT = "Unable to check for updates: {error}"

LABEL_WIDTH = "Width (px):"
LABEL_HEIGHT = "Height (px):"
LABEL_PRESET = "Preset:"
LABEL_RESULTING_CANVAS = "Result:"
LABEL_TILE_COLUMNS = "Tile columns:"
LABEL_TILE_ROWS = "Tile rows:"
LABEL_TILE_SIZE = "Tile size:"
BTN_OK = "OK"
BTN_OPEN_RELEASES = "Open releases"
BTN_CANCEL = "Cancel"
BTN_CLEAR = "Clear"
BTN_DISCARD = "Discard"
BTN_DISCARD_CHANGES = "Discard changes"
BTN_EMAIL = "Email"
BTN_FLATTEN_BACKGROUND = "Flatten background"
BTN_GITHUB = "GitHub"
BTN_IGNORE = "Ignore"
BTN_KEEP_EDITING = "Keep editing"
BTN_KEEP_TRANSPARENCY = "Keep transparency"
BTN_RESET_COLORS = "Reset"
BTN_RESET_ZOOM = "Reset Zoom"
BTN_OPEN_RECOVERY = "Open recovery"
BTN_SAVE = "Save"
BTN_SWAP_COLORS = "Swap"
BTN_GRID_COLOR = "Change grid color"
LABEL_BACKGROUND_COLOR = "Background:"
LABEL_CANVAS = "Canvas"
LABEL_CANVAS_SIZE = "Size:"
LABEL_COLORS = "Colors"
LABEL_GRID = "Grid:"
LABEL_INSPECTOR = "Inspector"
LABEL_PRIMARY_COLOR = "Primary:"
LABEL_PREVIEW = "Preview"
LABEL_RECENT_COLORS = "Recent colors:"
LABEL_ZOOM = "Zoom:"
TOOLBAR_TITLE = "Main Toolbar"

DIRTY_MARKER = "*"
UNTITLED_NAME = "Untitled"
WINDOW_TITLE_FMT = "{marker}{name} - " + APP_NAME
RESET_ZOOM_TOOLTIP_FMT = "Reset zoom to {zoom}x"

MSG_ICON_NOT_FOUND_FMT = "Tilf icon not found at: {path}"
MSG_STYLESHEET_LOADED_FMT = "Stylesheet loaded from: {path}"
MSG_STYLESHEET_MISSING_FMT = "Stylesheet not found at: {path}. Running with default style."
MSG_AUTOSAVE_SUCCESS_FMT = "Autosaved recovery file to: {path}"
MSG_AUTOSAVE_ERROR_FMT = "Error during autosave: {error}"
MSG_TOOL_WARNING_FMT = "Warning: Tool '{tool_name}' not found."

PROJECT_URL = "https://github.com/danterolle/tilf"
PROJECT_EMAIL_URL = "mailto:danterolle@catania.linux.it"
TITLE_CHECK_UPDATES = "Check for Updates"
TITLE_UPDATE_AVAILABLE = "Update Available"
TITLE_UPDATE_CURRENT = "Tilf is Up to Date"
TITLE_UPDATE_CHECK_FAILED = "Update Check Failed"
